/**
 * Brand marks for the technology arc, from simple-icons.
 *
 * Icons are imported by name so the bundler keeps only these ~67 of the
 * package's 3,400. A technology with no mark here falls back to a monogram
 * chip: Creo, Oracle, SQL Server, AWS, Azure, Heroku.
 */
import {
  siAkamai,
  siAngular,
  siAnsible,
  siAnsys,
  siAutocad,
  siAutodesk,
  siBentley,
  siC,
  siCloudflare,
  siCplusplus,
  siDassaultsystemes,
  siDigitalocean,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siExpress,
  siFirebase,
  siFlask,
  siGit,
  siGithubactions,
  siGo,
  siGooglecloud,
  siGrafana,
  siHuggingface,
  siJavascript,
  siJenkins,
  siJupyter,
  siKeras,
  siKotlin,
  siKubernetes,
  siLangchain,
  siLaravel,
  siMlflow,
  siMongodb,
  siMysql,
  siNetlify,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNumpy,
  siOpencv,
  siOpenjdk,
  siPandas,
  siPhp,
  siPostgresql,
  siPrometheus,
  siPython,
  siPytorch,
  siReact,
  siRedis,
  siRender,
  siRust,
  siScikitlearn,
  siSharp,
  siSketchup,
  siSpringboot,
  siSqlite,
  siStreamlit,
  siSupabase,
  siSvelte,
  siSwift,
  siTensorflow,
  siTerraform,
  siTypescript,
  siVercel,
  siVuedotjs,
} from "simple-icons";

/** 24×24 path data, keyed by the exact label used in content.ts. */
export const TECH_LOGO: Record<string, string> = {
  "Python": siPython.path,
  "Java": siOpenjdk.path,
  "C": siC.path,
  "C++": siCplusplus.path,
  "C#": siSharp.path,
  "JavaScript": siJavascript.path,
  "TypeScript": siTypescript.path,
  "Go": siGo.path,
  "Rust": siRust.path,
  "PHP": siPhp.path,
  "Swift": siSwift.path,
  "Kotlin": siKotlin.path,
  "React": siReact.path,
  "Next.js": siNextdotjs.path,
  "Angular": siAngular.path,
  "Vue": siVuedotjs.path,
  "Node.js": siNodedotjs.path,
  "Express": siExpress.path,
  "Django": siDjango.path,
  "Flask": siFlask.path,
  "Laravel": siLaravel.path,
  "Spring Boot": siSpringboot.path,
  ".NET": siDotnet.path,
  "Svelte": siSvelte.path,
  "TensorFlow": siTensorflow.path,
  "PyTorch": siPytorch.path,
  "Keras": siKeras.path,
  "scikit-learn": siScikitlearn.path,
  "Hugging Face": siHuggingface.path,
  "LangChain": siLangchain.path,
  "OpenCV": siOpencv.path,
  "Pandas": siPandas.path,
  "NumPy": siNumpy.path,
  "Jupyter": siJupyter.path,
  "Streamlit": siStreamlit.path,
  "MLflow": siMlflow.path,
  "AutoCAD": siAutocad.path,
  "SolidWorks": siDassaultsystemes.path,
  "CATIA": siDassaultsystemes.path,
  "Fusion 360": siAutodesk.path,
  "Revit": siAutodesk.path,
  "STAAD Pro": siBentley.path,
  "ANSYS": siAnsys.path,
  "3ds Max": siAutodesk.path,
  "SketchUp": siSketchup.path,
  "MySQL": siMysql.path,
  "PostgreSQL": siPostgresql.path,
  "MongoDB": siMongodb.path,
  "Redis": siRedis.path,
  "SQLite": siSqlite.path,
  "Firebase": siFirebase.path,
  "Supabase": siSupabase.path,
  "Elasticsearch": siElasticsearch.path,
  "Docker": siDocker.path,
  "Kubernetes": siKubernetes.path,
  "Jenkins": siJenkins.path,
  "Git": siGit.path,
  "GitHub Actions": siGithubactions.path,
  "Terraform": siTerraform.path,
  "Ansible": siAnsible.path,
  "Nginx": siNginx.path,
  "Prometheus": siPrometheus.path,
  "Grafana": siGrafana.path,
  "Google Cloud": siGooglecloud.path,
  "Vercel": siVercel.path,
  "Netlify": siNetlify.path,
  "Cloudflare": siCloudflare.path,
  "DigitalOcean": siDigitalocean.path,
  "Linode": siAkamai.path,
  "Render": siRender.path,
};
